# Database configuration
db-data-source: "root:@tcp(localhost:3306)/token13_app?charset=utf8mb4&parseTime=True&loc=Local"
#  "root:password@tcp(localhost:3306)/token13_app?charset=utf8mb4&parseTime=True&loc=Local"
db-config:
  maxConn: 20
  idleConn: 10
  maxLeftTime: 3600

# TronGrid API configuration
trongrid:
  url: "https://api.trongrid.io"
  api-key: "your-trongrid-api-key"

# QuickNode API configuration
quicknode:
  kv-list-endpoint: "https://api.quicknode.com/kv/rest/v1/lists/watched-addresses"
  api-key: "QN_9cd844189f744fb093e269bcc4804aaf"
  update-api-key: "QN_abfe2027e7034d05a3a99466061acc37"

# Sync configuration
sync:
  address-sync-interval: "1h"
  transaction-fetch-interval: "15m"