name: Quicknode Build and Deploy on VM


on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start ssh-agent and add private key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_QUICKNODE_PRIVATE_KEY }}

      - name: Set image variables
        id: vars
        run: |
          echo "IMAGE_NAME=${{ secrets.MY_QUICKREGISTRY_DOMAIN }}/quicknode:latest" >> "$GITHUB_ENV"
          echo "BASE_IMAGE=${{ secrets.MY_QUICKREGISTRY_DOMAIN }}/golang:1.23.6-alpine" >> "$GITHUB_ENV"

      - name: Build Docker image using private base image
        run: |
          echo "Building Docker image with base image: $BASE_IMAGE"

          sudo docker build \
            --build-arg BASE_IMAGE=$BASE_IMAGE \
            -t $IMAGE_NAME .

      - name: Transfer image to remote VM and load it
        run: |
          echo "Saving and transferring image to remote VM..."
          sudo docker save $IMAGE_NAME | \
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker load"

      - name: Push image to private registry from remote VM
        run: |
          echo "Pushing image to private registry from remote VM..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker push $IMAGE_NAME"


      - name: Deploy container on remote VM
        run: |
          echo "Deploying container on remote VM..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            docker stop quicknode || true && \
            docker rm quicknode || true && \
            docker run -d --name quicknode \
              -p 8800:8800 \
              -e apollo_namespace=config_main.yaml \
              --restart always \
              $IMAGE_NAME
          "
